# Generated by Django 6.0.2 on 2026-03-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='waiting', max_length=20),
        ),
    ]
