# Generated by Django 6.0.2 on 2026-03-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('selected', 'Selected'), ('rejected', 'Rejected')], default='waiting', max_length=10),
        ),
    ]
